LCIDs = {
'af': {'locale': "Afrikaans", 'language': "af", 'LCID': 1078, 'codepage': 1252},
'sq': {'locale': "Albanian", 'language': "sq", 'LCID': 1052, 'codepage': 1250},
'am': {'locale': "Amharic", 'language': "am", 'LCID': 1118, 'codepage': 0},
'ar-dz': {'locale': "Arabic - Algeria", 'language': "ar", 'LCID': 5121, 'codepage': 1256},
'ar-bh': {'locale': "Arabic - Bahrain", 'language': "ar", 'LCID': 15361, 'codepage': 1256},
'ar-eg': {'locale': "Arabic - Egypt", 'language': "ar", 'LCID': 3073, 'codepage': 1256},
'ar-iq': {'locale': "Arabic - Iraq", 'language': "ar", 'LCID': 2049, 'codepage': 1256},
'ar-jo': {'locale': "Arabic - Jordan", 'language': "ar", 'LCID': 11265, 'codepage': 1256},
'ar-kw': {'locale': "Arabic - Kuwait", 'language': "ar", 'LCID': 13313, 'codepage': 1256},
'ar-lb': {'locale': "Arabic - Lebanon", 'language': "ar", 'LCID': 12289, 'codepage': 1256},
'ar-ly': {'locale': "Arabic - Libya", 'language': "ar", 'LCID': 4097, 'codepage': 1256},
'ar-ma': {'locale': "Arabic - Morocco", 'language': "ar", 'LCID': 6145, 'codepage': 1256},
'ar-om': {'locale': "Arabic - Oman", 'language': "ar", 'LCID': 8193, 'codepage': 1256},
'ar-qa': {'locale': "Arabic - Qatar", 'language': "ar", 'LCID': 16385, 'codepage': 1256},
'ar-sa': {'locale': "Arabic - Saudi Arabia", 'language': "ar", 'LCID': 1025, 'codepage': 1256},
'ar-sy': {'locale': "Arabic - Syria", 'language': "ar", 'LCID': 10241, 'codepage': 1256},
'ar-tn': {'locale': "Arabic - Tunisia", 'language': "ar", 'LCID': 7169, 'codepage': 1256},
'ar-ae': {'locale': "Arabic - United Arab Emirates", 'language': "ar", 'LCID': 14337, 'codepage': 1256},
'ar-ye': {'locale': "Arabic - Yemen", 'language': "ar", 'LCID': 9217, 'codepage': 1256},
'hy': {'locale': "Armenian", 'language': "hy", 'LCID': 1067, 'codepage': 0},
'as': {'locale': "Assamese", 'language': "as", 'LCID': 1101, 'codepage': 0},
'az-az': {'locale': "Azeri - Cyrillic", 'language': "az", 'LCID': 2092, 'codepage': 1251},
'az-az': {'locale': "Azeri - Latin", 'language': "az", 'LCID': 1068, 'codepage': 1254},
'eu': {'locale': "Basque", 'language': "eu", 'LCID': 1069, 'codepage': 1252},
'be': {'locale': "Belarusian", 'language': "be", 'LCID': 1059, 'codepage': 1251},
'bn': {'locale': "Bengali - Bangladesh", 'language': "bn", 'LCID': 2117, 'codepage': 0},
'bn': {'locale': "Bengali - India", 'language': "bn", 'LCID': 1093, 'codepage': 0},
'bs': {'locale': "Bosnian", 'language': "bs", 'LCID': 5146, 'codepage': 0},
'bg': {'locale': "Bulgarian", 'language': "bg", 'LCID': 1026, 'codepage': 1251},
'my': {'locale': "Burmese", 'language': "my", 'LCID': 1109, 'codepage': 0},
'ca': {'locale': "Catalan", 'language': "ca", 'LCID': 1027, 'codepage': 1252},
'zh-cn': {'locale': "Chinese - China", 'language': "zh", 'LCID': 2052, 'codepage': 0},
'zh-hk': {'locale': "Chinese - Hong Kong SAR", 'language': "zh", 'LCID': 3076, 'codepage': 0},
'zh-mo': {'locale': "Chinese - Macau SAR", 'language': "zh", 'LCID': 5124, 'codepage': 0},
'zh-sg': {'locale': "Chinese - Singapore", 'language': "zh", 'LCID': 4100, 'codepage': 0},
'zh-tw': {'locale': "Chinese - Taiwan", 'language': "zh", 'LCID': 1028, 'codepage': 0},
'hr': {'locale': "Croatian", 'language': "hr", 'LCID': 1050, 'codepage': 1250},
'cs': {'locale': "Czech", 'language': "cs", 'LCID': 1029, 'codepage': 1250},
'cs-cz': {'locale': "Czech", 'language': "cs", 'LCID': 1029, 'codepage': 1250},
'da': {'locale': "Danish", 'language': "da", 'LCID': 1030, 'codepage': 1252},
'dv': {'locale': "Divehi; Dhivehi; Maldivian", 'language': "dv", 'LCID':  1125, 'codepage': 0},
'nl-be': {'locale': "Dutch - Belgium", 'language': "nl", 'LCID': 2067, 'codepage': 1252},
'nl-nl': {'locale': "Dutch - Netherlands", 'language': "nl", 'LCID': 1043, 'codepage': 1252},
'en-au': {'locale': "English - Australia", 'language': "en", 'LCID': 3081, 'codepage': 1252},
'en-bz': {'locale': "English - Belize", 'language': "en", 'LCID': 10249, 'codepage': 1252},
'en-ca': {'locale': "English - Canada", 'language': "en", 'LCID': 4105, 'codepage': 1252},
'en-cb': {'locale': "English - Caribbean", 'language': "en", 'LCID': 9225, 'codepage': 1252},
'en-gb': {'locale': "English - Great Britain", 'language': "en", 'LCID': 2057, 'codepage': 1252},
'en-in': {'locale': "English - India", 'language': "en", 'LCID': 16393, 'codepage': 0},
'en-ie': {'locale': "English - Ireland", 'language': "en", 'LCID': 6153, 'codepage': 1252},
'en-jm': {'locale': "English - Jamaica", 'language': "en", 'LCID': 8201, 'codepage': 1252},
'en-nz': {'locale': "English - New Zealand", 'language': "en", 'LCID': 5129, 'codepage': 1252},
'en-ph': {'locale': "English - Phillippines", 'language': "en", 'LCID': 13321, 'codepage': 1252},
'en-za': {'locale': "English - Southern Africa", 'language': "en", 'LCID': 7177, 'codepage': 1252},
'en-tt': {'locale': "English - Trinidad", 'language': "en", 'LCID': 11273, 'codepage': 1252},
'en-us': {'locale': "English - United States", 'language': "en", 'LCID': 1033, 'codepage': 1252},
'et': {'locale': "Estonian", 'language': "et", 'LCID': 1061, 'codepage': 1257},
'mk': {'locale': "FYRO Macedonia", 'language': "mk", 'LCID': 1071, 'codepage': 1251},
'fo': {'locale': "Faroese", 'language': "fo", 'LCID': 1080, 'codepage': 1252},
'fa': {'locale': "Farsi - Persian", 'language': "fa", 'LCID': 1065, 'codepage': 1256},
'fi': {'locale': "Finnish", 'language': "fi", 'LCID': 1035, 'codepage': 1252},
'fr-be': {'locale': "French - Belgium", 'language': "fr", 'LCID': 2060, 'codepage': 1252},
'fr-ca': {'locale': "French - Canada", 'language': "fr", 'LCID': 3084, 'codepage': 1252},
'fr-fr': {'locale': "French - France", 'language': "fr", 'LCID': 1036, 'codepage': 1252},
'fr-lu': {'locale': "French - Luxembourg", 'language': "fr", 'LCID': 5132, 'codepage': 1252},
'fr-ch': {'locale': "French - Switzerland", 'language': "fr", 'LCID': 4108, 'codepage': 1252},
'gd-ie': {'locale': "Gaelic - Ireland", 'language': "gd", 'LCID': 2108, 'codepage': 0},
'gd': {'locale': "Gaelic - Scotland", 'language': "gd", 'LCID': 1084, 'codepage': 0},
'de-at': {'locale': "German - Austria", 'language': "de", 'LCID': 3079, 'codepage': 1252},
'de-de': {'locale': "German - Germany", 'language': "de", 'LCID': 1031, 'codepage': 1252},
'de-li': {'locale': "German - Liechtenstein", 'language': "de", 'LCID': 5127, 'codepage': 1252},
'de-lu': {'locale': "German - Luxembourg", 'language': "de", 'LCID': 4103, 'codepage': 1252},
'de-ch': {'locale': "German - Switzerland", 'language': "de", 'LCID': 2055, 'codepage': 1252},
'el': {'locale': "Greek", 'language': "el", 'LCID': 1032, 'codepage': 1253},
'gn': {'locale': "Guarani - Paraguay", 'language': "gn", 'LCID': 1140, 'codepage': 0},
'gu': {'locale': "Gujarati", 'language': "gu", 'LCID': 1095, 'codepage': 0},
'he': {'locale': "Hebrew", 'language': "he", 'LCID': 1037, 'codepage': 1255},
'hi': {'locale': "Hindi", 'language': "hi", 'LCID': 1081, 'codepage': 0},
'hu': {'locale': "Hungarian", 'language': "hu", 'LCID': 1038, 'codepage': 1250},
'is': {'locale': "Icelandic", 'language': "is", 'LCID': 1039, 'codepage': 1252},
'id': {'locale': "Indonesian", 'language': "id", 'LCID': 1057, 'codepage': 1252},
'it-it': {'locale': "Italian - Italy", 'language': "it", 'LCID': 1040, 'codepage': 1252},
'it-ch': {'locale': "Italian - Switzerland", 'language': "it", 'LCID': 2064, 'codepage': 1252},
'ja': {'locale': "Japanese", 'language': "ja", 'LCID': 1041, 'codepage': 0},
'kn': {'locale': "Kannada", 'language': "kn", 'LCID': 1099, 'codepage': 0},
'ks': {'locale': "Kashmiri", 'language': "ks", 'LCID': 1120, 'codepage': 0},
'kk': {'locale': "Kazakh", 'language': "kk", 'LCID': 1087, 'codepage': 1251},
'km': {'locale': "Khmer", 'language': "km", 'LCID': 1107, 'codepage': 0},
'ko': {'locale': "Korean", 'language': "ko", 'LCID': 1042, 'codepage': 0},
'lo': {'locale': "Lao", 'language': "lo", 'LCID': 1108, 'codepage': 0},
'la': {'locale': "Latin", 'language': "la", 'LCID': 1142, 'codepage': 0},
'lv': {'locale': "Latvian", 'language': "lv", 'LCID': 1062, 'codepage': 1257},
'lt': {'locale': "Lithuanian", 'language': "lt", 'LCID': 1063, 'codepage': 1257},
'ms-bn': {'locale': "Malay - Brunei", 'language': "ms", 'LCID': 2110, 'codepage': 1252},
'ms-my': {'locale': "Malay - Malaysia", 'language': "ms", 'LCID': 1086, 'codepage': 1252},
'ml': {'locale': "Malayalam", 'language': "ml", 'LCID': 1100, 'codepage': 0},
'mt': {'locale': "Maltese", 'language': "mt", 'LCID': 1082, 'codepage': 0},
'mi': {'locale': "Maori", 'language': "mi", 'LCID': 1153, 'codepage': 0},
'mr': {'locale': "Marathi", 'language': "mr", 'LCID': 1102, 'codepage': 0},
'mn': {'locale': "Mongolian", 'language': "mn", 'LCID': 2128, 'codepage': 0},
'mn': {'locale': "Mongolian", 'language': "mn", 'LCID': 1104, 'codepage': 1251},
'ne': {'locale': "Nepali", 'language': "ne", 'LCID': 1121, 'codepage': 0},
'no-no': {'locale': "Norwegian - Bokml", 'language': "nb", 'LCID': 1044, 'codepage': 1252},
'no-no': {'locale': "Norwegian - Nynorsk", 'language': "nn", 'LCID': 2068, 'codepage': 1252},
'or': {'locale': "Oriya", 'language': "or", 'LCID': 1096, 'codepage': 0},
'pl': {'locale': "Polish", 'language': "pl", 'LCID': 1045, 'codepage': 1250},
'pt-br': {'locale': "Portuguese - Brazil", 'language': "pt", 'LCID': 1046, 'codepage': 1252},
'pt-pt': {'locale': "Portuguese - Portugal", 'language': "pt", 'LCID': 2070, 'codepage': 1252},
'pa': {'locale': "Punjabi", 'language': "pa", 'LCID': 1094, 'codepage': 0},
'rm': {'locale': "Raeto-Romance", 'language': "rm", 'LCID': 1047, 'codepage': 0},
'ro-mo': {'locale': "Romanian - Moldova", 'language': "ro", 'LCID': 2072, 'codepage': 0},
'ro': {'locale': "Romanian - Romania", 'language': "ro", 'LCID': 1048, 'codepage': 1250},
'ru': {'locale': "Russian", 'language': "ru", 'LCID': 1049, 'codepage': 1251},
'ru-mo': {'locale': "Russian - Moldova", 'language': "ru", 'LCID': 2073, 'codepage': 0},
'sa': {'locale': "Sanskrit", 'language': "sa", 'LCID': 1103, 'codepage': 0},
'sr-sp': {'locale': "Serbian - Cyrillic", 'language': "sr", 'LCID': 3098, 'codepage': 1251},
'sr-sp': {'locale': "Serbian - Latin", 'language': "sr", 'LCID': 2074, 'codepage': 1250},
'tn': {'locale': "Setsuana", 'language': "tn", 'LCID': 1074, 'codepage': 0},
'sd': {'locale': "Sindhi", 'language': "sd", 'LCID': 1113, 'codepage': 0},
'si': {'locale': "Sinhala; Sinhalese", 'language': "si", 'LCID': 1115, 'codepage': 0},
'sk': {'locale': "Slovak", 'language': "sk", 'LCID': 1051, 'codepage': 1250},
'sl': {'locale': "Slovenian", 'language': "sl", 'LCID': 1060, 'codepage': 1250},
'so': {'locale': "Somali", 'language': "so", 'LCID': 1143, 'codepage': 0},
'sb': {'locale': "Sorbian", 'language': "sb", 'LCID': 1070, 'codepage': 0},
'es-ar': {'locale': "Spanish - Argentina", 'language': "es", 'LCID': 11274, 'codepage': 1252},
'es-bo': {'locale': "Spanish - Bolivia", 'language': "es", 'LCID': 16394, 'codepage': 1252},
'es-cl': {'locale': "Spanish - Chile", 'language': "es", 'LCID': 13322, 'codepage': 1252},
'es-co': {'locale': "Spanish - Colombia", 'language': "es", 'LCID': 9226, 'codepage': 1252},
'es-cr': {'locale': "Spanish - Costa Rica", 'language': "es", 'LCID': 5130, 'codepage': 1252},
'es-do': {'locale': "Spanish - Dominican Republic", 'language': "es", 'LCID': 7178, 'codepage': 1252},
'es-ec': {'locale': "Spanish - Ecuador", 'language': "es", 'LCID': 12298, 'codepage': 1252},
'es-sv': {'locale': "Spanish - El Salvador", 'language': "es", 'LCID': 17418, 'codepage': 1252},
'es-gt': {'locale': "Spanish - Guatemala", 'language': "es", 'LCID': 4106, 'codepage': 1252},
'es-hn': {'locale': "Spanish - Honduras", 'language': "es", 'LCID': 18442, 'codepage': 1252},
'es-mx': {'locale': "Spanish - Mexico", 'language': "es", 'LCID': 2058, 'codepage': 1252},
'es-ni': {'locale': "Spanish - Nicaragua", 'language': "es", 'LCID': 19466, 'codepage': 1252},
'es-pa': {'locale': "Spanish - Panama", 'language': "es", 'LCID': 6154, 'codepage': 1252},
'es-py': {'locale': "Spanish - Paraguay", 'language': "es", 'LCID': 15370, 'codepage': 1252},
'es-pe': {'locale': "Spanish - Peru", 'language': "es", 'LCID': 10250, 'codepage': 1252},
'es-pr': {'locale': "Spanish - Puerto Rico", 'language': "es", 'LCID': 20490, 'codepage': 1252},
'es-es': {'locale': "Spanish - Spain (Traditional)", 'language': "es", 'LCID': 1034, 'codepage': 1252},
'es-uy': {'locale': "Spanish - Uruguay", 'language': "es", 'LCID': 14346, 'codepage': 1252},
'es-ve': {'locale': "Spanish - Venezuela", 'language': "es", 'LCID': 8202, 'codepage': 1252},
'sw': {'locale': "Swahili", 'language': "sw", 'LCID': 1089, 'codepage': 1252},
'sv-fi': {'locale': "Swedish - Finland", 'language': "sv", 'LCID': 2077, 'codepage': 1252},
'sv-se': {'locale': "Swedish - Sweden", 'language': "sv", 'LCID': 1053, 'codepage': 1252},
'tg': {'locale': "Tajik", 'language': "tg", 'LCID': 1064, 'codepage': 0},
'ta': {'locale': "Tamil", 'language': "ta", 'LCID': 1097, 'codepage': 0},
'tt': {'locale': "Tatar", 'language': "tt", 'LCID': 1092, 'codepage': 1251},
'te': {'locale': "Telugu", 'language': "te", 'LCID': 1098, 'codepage': 0},
'th': {'locale': "Thai", 'language': "th", 'LCID': 1054, 'codepage': 0},
'bo': {'locale': "Tibetan", 'language': "bo", 'LCID': 1105, 'codepage': 0},
'ts': {'locale': "Tsonga", 'language': "ts", 'LCID': 1073, 'codepage': 0},
'tr': {'locale': "Turkish", 'language': "tr", 'LCID': 1055, 'codepage': 1254},
'tk': {'locale': "Turkmen", 'language': "tk", 'LCID': 1090, 'codepage': 0},
'uk': {'locale': "Ukrainian", 'language': "uk", 'LCID': 1058, 'codepage': 1251},
'UTF-8': {'locale': "Unicode", 'language': "", 'LCID': 0, 'codepage': 0},
'ur': {'locale': "Urdu", 'language': "ur", 'LCID': 1056, 'codepage': 1256},
'uz-uz': {'locale': "Uzbek - Cyrillic", 'language': "uz", 'LCID': 2115, 'codepage': 1251},
'uz-uz': {'locale': "Uzbek - Latin", 'language': "uz", 'LCID': 1091, 'codepage': 1254},
'vi': {'locale': "Vietnamese", 'language': "vi", 'LCID': 1066, 'codepage': 1258},
'cy': {'locale': "Welsh", 'language': "cy", 'LCID': 1106, 'codepage': 0},
'xh': {'locale': "Xhosa", 'language': "xh", 'LCID': 1076, 'codepage': 0},
'yi': {'locale': "Yiddish", 'language': "yi", 'LCID': 1085, 'codepage': 0},
'zu': {'locale': "Zulu", 'language': "zu", 'LCID': 1077, 'codepage': 0},
};
